export const GET_LIST_TEST_GEN = 'GET_LIST_TEST_GEN';
export const GET_LIST_TEST_GEN_SUCCESS = 'GET_LIST_TEST_GEN_SUCCESS';

export const GET_GENERAL_KEY_LIST = 'GET_GENERAL_KEY_LIST';
export const GET_GENERAL_KEY_LIST_SUCCESS = 'GET_GENERAL_KEY_LIST_SUCCESS';

export const GET_LIST_COUNTRY = 'GET_LIST_COUNTRY';
export const GET_LIST_COUNTRY_SUCCESS = 'GET_LIST_COUNTRY_SUCCESS';

export const GET_LIST_CITY = 'GET_LIST_CITY';
export const GET_LIST_CITY_SUCCESS = 'GET_LIST_CITY_SUCCESS';
