export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';

export const GET_RELATED_POSTS = 'GET_RELATED_POSTS';
export const GET_RELATED_POSTS_SUCCESS = 'GET_RELATED_POSTS_SUCCESS';

export const GET_MOST_LIKE_POSTS = 'GET_MOST_LIKE_POSTS';
export const GET_MOST_LIKE_POSTS_SUCCESS = 'GET_MOST_LIKE_POSTS_SUCCESS';

export const GET_POST_CATEGORY = 'GET_POST_CATEGORY';
export const GET_POST_CATEGORY_SUCCESS = 'GET_POST_CATEGORY_SUCCESS';

export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';

