export const GET_REFERRAL = 'GET_REFERRAL';
export const GET_REFERRAL_SUCCESS = 'GET_REFERRAL_SUCCESS';
export const GET_YOUR_NETWORK = 'GET_YOUR_NETWORK';
export const GET_YOUR_NETWORK_SUCCESS = 'GET_YOUR_NETWORK_SUCCESS';
