export const GET_LIST_ORDER = 'GET_LIST_ORDER';
export const GET_LIST_ORDER_SUCCESS = 'GET_LIST_ORDER_SUCCESS';
export const GET_DETAIL_ORDER = 'GET_DETAIL_ORDER';
export const GET_DETAIL_ORDER_SUCCESS ='GET_DETAIL_ORDER_SUCCESS';
