export const GET_LIST_MEMBERSHIP_PLAN = "GET_LIST_MEMBERSHIP_PLAN";
export const GET_LIST_MEMBERSHIP_PLAN_SUCCESS = "GET_LIST_MEMBERSHIP_PLAN_SUCCESS";

export const SET_CART_DATA = "SET_CART_DATA";
export const SET_CART_STEP = "SET_CART_STEP";

export const PAYMENT_ORDER = "PAYMENT_ORDER";
export const PAYMENT_ORDER_SUCCESS = "PAYMENT_ORDER_SUCCESS";