
export const CUSTOMER_MEDICAL_FILE_LIST = 'CUSTOMER_MEDICAL_FILE_LIST';
export const CUSTOMER_MEDICAL_FILE_LIST_SUCCESS = 'CUSTOMER_MEDICAL_FILE_LIST_SUCCESS';

export const CUSTOMER_MEDICAL_FILE_CREATE = 'CUSTOMER_MEDICAL_FILE_CREATE';
export const CUSTOMER_MEDICAL_FILE_CREATE_SUCCESS = 'CUSTOMER_MEDICAL_FILE_CREATE_SUCCESS';

export const CUSTOMER_MEDICAL_FILE_DELETE = 'CUSTOMER_MEDICAL_FILE_DELETE';
export const CUSTOMER_MEDICAL_FILE_DELETE_SUCCESS = 'CUSTOMER_MEDICAL_FILE_DELETE_SUCCESS';