export const GET_GENERAL_KEY_LIST = "HEALTH_PROFILE_GET_GENERAL_KEY_LIST";
export const GET_GENERAL_KEY_LIST_SUCCESS = "HEALTH_PROFILE_GET_GENERAL_KEY_LIST_SUCCESS";

export const CREATE_CUSTOMER_INSURANCE = "CREATE_CUSTOMER_INSURANCE";
export const UPDATE_CUSTOMER_INSURANCE = "UPDATE_CUSTOMER_INSURANCE";
export const CREATE_CUSTOMER_INSURANCE_SUCCESS = "CREATE_CUSTOMER_INSURANCE_SUCCESS";
export const UPDATE_CUSTOMER_INSURANCE_SUCCESS = "UPDATE_CUSTOMER_INSURANCE_SUCCESS";

export const DELETE_CUSTOMER_INSURANCE = 'DELETE_CUSTOMER_INSURANCE';
export const DELETE_CUSTOMER_INSURANCE_SUCCESS = 'DELETE_CUSTOMER_INSURANCE_SUCCESS';

export const CREATE_CUSTOMER_HEALTH = 'CREATE_CUSTOMER_HEALTH';
export const CREATE_CUSTOMER_HEALTH_SUCCESS = 'CREATE_CUSTOMER_HEALTH_SUCCESS';

export const UPDATE_CUSTOMER_HEALTH = 'UPDATE_CUSTOMER_HEALTH';
export const UPDATE_CUSTOMER_HEALTH_SUCCESS = 'UPDATE_CUSTOMER_HEALTH_SUCCESS';

export const DELETE_CUSTOMER_HEALTH = 'DELETE_CUSTOMER_HEALTH';
export const DELETE_CUSTOMER_HEALTH_SUCCESS = 'DELETE_CUSTOMER_HEALTH_SUCCESS';

export const CREATE_CUSTOMER_FAMILY = 'CREATE_CUSTOMER_FAMILY';
export const CREATE_CUSTOMER_FAMILY_SUCCESS = 'CREATE_CUSTOMER_FAMILY_SUCCESS';

export const UPDATE_CUSTOMER_FAMILY = 'UPDATE_CUSTOMER_FAMILY';
export const UPDATE_CUSTOMER_FAMILY_SUCCESS = 'UPDATE_CUSTOMER_FAMILY_SUCCESS';

export const DELETE_CUSTOMER_FAMILY = 'DELETE_CUSTOMER_FAMILY';
export const DELETE_CUSTOMER_FAMILY_SUCCESS = 'DELETE_CUSTOMER_FAMILY_SUCCESS';
