// Medical
export const RESET_MEDICAL = 'RESET_MEDICAL';
export const GET_MEDICAL = 'GET_MEDICAL';
export const GET_MEDICAL_SUCCESS = 'GET_MEDICAL_SUCCESS';
export const LOAD_MORE_MEDICAL_PROFILE = 'LOAD_MORE_MEDICAL_PROFILE';
export const LOAD_MORE_MEDICAL_PROFILE_SUCCESS = 'LOAD_MORE_MEDICAL_PROFILE_SUCCESS';
