export const GET_LIST_MEMBERSHIP_PLAN = "GET_LIST_MEMBERSHIP_PLAN";
export const GET_LIST_MEMBERSHIP_PLAN_SUCCESS = "GET_LIST_MEMBERSHIP_PLAN_SUCCESS"; 

export const GET_MY_MEMBERSHIP = "GET_MY_MEMBERSHIP";
export const GET_MY_MEMBERSHIP_SUCCESS = "GET_MY_MEMBERSHIP_SUCCESS";

export const MASTER_GET_BY_TYPE = 'MASTER_GET_BY_TYPE';
export const MASTER_GET_BY_TYPE_SUCCESS = 'MASTER_GET_BY_TYPE_SUCCESS';

export const CHECK_COUPON = 'CHECK_COUPON';

export const CHANGE_MEMBERSHIP = 'CHANGE_MEMBERSHIP';