export const GET_WALLET = "GET_WALLET";
export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS";

export const EXCHANGE_GET_RATE = "EXCHANGE_GET_RATE";
export const EXCHANGE_GET_RATE_SUCCESS = "EXCHANGE_GET_RATE_SUCCESS";

export const EXCHANGE_CAL_RATE = "EXCHANGE_CAL_RATE";
export const EXCHANGE_CAL_RATE_SUCCESS = "EXCHANGE_CAL_RATE_SUCCESS";

export const WALLET_TRAN_DEPOSIT_ONLINE = "WALLET_TRAN_DEPOSIT_ONLINE";
export const WALLET_TRAN_DEPOSIT_CHECK = "WALLET_TRAN_DEPOSIT_CHECK";

export const WALLET_TRAN_LIST = "WALLET_TRAN_LIST";
export const WALLET_TRAN_LIST_SUCCESS = "WALLET_TRAN_LIST_SUCCESS";

export const WALLET_TRAN_WITHDRAW = "WALLET_TRAN_WITHDRAW";
export const WALLET_TRAN_WITHDRAW_SUCCESS = "WALLET_TRAN_WITHDRAW_SUCCESS";

export const WALLET_TRAN_TRANSFER = "WALLET_TRAN_TRANSFER";
export const WALLET_TRAN_TRANSFER_SUCCESS = "WALLET_TRAN_TRANSFER_SUCCESS";

export const MASTER_SERVICE = "DASHBOARD_MASTER_SERVICE";
export const MASTER_SERVICE_SUCCESS = "DASHBOARD_MASTER_SERVICE_SUCCESS";

export const GET_BANK_LIST = "DASHBOARD_GET_BANK_LIST";
export const GET_BANK_LIST_SUCCESS = "DASHBOARD_GET_BANK_LIST_SUCCESS";

export const GET_DASHBOARD = "DASHBOARD_GET_DASHBOARD";
export const GET_DASHBOARD_SUCCESS = "DASHBOARD_GET_DASHBOARD_SUCCESS";

export const WALLET_GET_BY_EMAIL_OR_ADDRESS = "WALLET_GET_BY_EMAIL_OR_ADDRESS";

export const INVITE_FRIEND = "DASHBOARD_INVITE_FRIEND";

export const GET_LIST_POST_DASHBOARD = "GET_LIST_POST_DASHBOARD";
export const GET_LIST_POST_DASHBOARD_SUCCESS =
  "GET_LIST_POST_DASHBOARD_SUCCESS";

export const GET_LIST_POST_CATE_DASHBOARD = "GET_LIST_POST_CATE_DASHBOARD";
export const GET_LIST_POST_CATE_DASHBOARD_SUCCESS =
  "GET_LIST_POST_CATE_DASHBOARD_SUCCESS";

export const GET_LIST_NOTIFICATION_DASHBOARD =
  "GET_LIST_NOTIFICATION_DASHBOARD";
export const GET_LIST_NOTIFICATION_DASHBOARD_SUCCESS =
  "GET_LIST_NOTIFICATION_DASHBOARD_SUCCESS";

export const GET_RATE = "GET_RATE";
export const GET_RATE_SUCCESS = "GET_RATE_SUCCESS";

export const READ_NOTIFICATION = "READ_NOTIFICATION";
export const READ_NOTIFICATION_SUCCESS = "READ_NOTIFICATION_SUCCESS";

export const GET_ADMIN_BANK = "GET_ADMIN_BANK";
export const GET_ADMIN_BANK_SUCCESS = "GET_ADMIN_BANK_SUCCESS";

export const SWAP_WITHDRAW = "SWAP_WITHDRAW";
export const SWAP_WITHDRAW_SUCCESS = "SWAP_WITHDRAW_SUCCESS";

export const CONFIRM_CURRENCY = "CONFIRM_CURRENCY";

export const WALLET_WITHDRAW_TRANSFER = "WALLET_WITHDRAW_TRANSFER";
export const WALLET_WITHDRAW_SUCCESS = "WALLET_WITHDRAW_SUCCESS";
